# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db87101021f9790edfe7b752430a2bc08595fca6db490841a1224a8333564f27409d814a4a50e2308b653a0d149a0546fa1587113c5bcf8ca4119a03dd696e78

test:
  secret_key_base: aeb63f6f0f5b3e0982e8f1919c4a24cfdd47af4064dd0992e5350ac0c1f6d7fe72fe1c4c062db29f322a6362deeb872b207ba9be0a9ce2018aea0598f58f179b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
